### ISSUE TITLE
Easy to bulk add to collection

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#105]
we need checkboxes next to the scarfs for add/want/trade in the search view for an easy way to add several items with one submit.

**Comment by cmazuc** [comment]
I think the proper way to implement this would be to use javascript to hit the update url directly instead of adding more forms. It would be trivial to modify the code to return a json response instead of rendering a page or redirect.

**Comment by cmazuc** [comment]
I played around with this long enough to confirm that frontend work is not a good use of my time. I reworked the backend code a bit and documented how to use it:

URL: /item/<item_id>/<action>
Methods: GET, POST
 
Update or query the logged in user's record for an item.
 
If a POST request is received then the current record is returned instead of a redirect back to the previous page.
 
Allowed actions:
'status'    - Return the item's current status
'have'      - Mark an item as part of the user's collection
'donthave'  - Remove the item from the user's collection
'show'      - If the item is in the user's collection mark it as visible to others
'hide'      - If the item is in the user's collection hide it from others
'willtrade' - Mark the item as available for trade
'wonttrade' - Don't show this item as available for trade
'want'      - Add this item to the user's want list
'dontwant ' - Remove this item from the user's want list
 
Sample record:
{"hidden": 1, "want": 0, "have": 1, "willtrade": 0}

**Comment by cmazuc** [comment]
#98 and #95 are pretty much duplicates of this, any time we display an item we should also display collection controls alongside.

**Comment by cmazuc** [comment]
I played around with this some more and this is what I came up with:

https://github.com/cmazuc/scarfage/commit/788f255be7a87c4391f324750c54b6ebb8e783c4

I'm certain there's a cleaner way to do this but it's a functional proof of concept.

**Comment by cmazuc** [comment]
This commit cleans things up a bit and adds actions to the search results page. The icons kinda suck but we should be able to do something like this whenever we display a scarf.

https://github.com/cmazuc/scarfage/commit/f03c6721426d765a2371b9138435bfcbeeddedd0

**Comment by subiki** [comment]
@cherz can you update the rest of the site templates to include the java code? Collections still need to refresh the page for an action.

https://www.scarfage.com/user/scarfage#collections
