### ISSUE TITLE
Home page link borked in menu

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#120]
The link back to the landing page from the top menu is broken.
Click on "Scarfage" and nothing happens.

**Comment by subiki** [comment]
Mobile apparently works though.

**Comment by subiki** [comment]
still borked. Desktop version of the site does not have a link to the landing page from the Scarfage button up top.

**Comment by cmazuc** [comment]
Not a code issue, static files are hosted via CloudFront and cached for a while so updates won't be immediate. I've issued a cache invalidation so that should force the update, give it a few minutes and retry. Long-term I'm going to modify the deployment system to add file hashes to the filenames of everything in the static directory so we won't need to do this when making changes.
